name := "Data Munging Corr"
version := "1.0"
scalaVersion :=  "2.11.5"
libraryDependencies += "org.apache.spark" %% "spark-core" % "1.5.2"
libraryDependencies += "com.databricks" % "spark-csv_2.10" % "1.3.0"
